name: 0.2.$(rev:r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'


steps:
- checkout: self
  clean: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- script: |
   cd $(Build.SourcesDirectory)/src/Saxx.Storyblok.Example
   dotnet setversion $(Build.BuildNumber)
  displayName: Set Version

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish Example Website
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: DotNetCoreCLI@2
  displayName: Pack Saxx.Storyblok NuGet package
  inputs:
    command: pack
    packagesToPack: 'src/Saxx.Storyblok/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: Pack Saxx.Storyblok.Components NuGet package
  inputs:
    command: pack
    packagesToPack: 'src/Saxx.Storyblok.Components/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: Push to public NuGet
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Public NuGet'

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
