name: 2.1.$(rev:r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'


steps:
- checkout: self

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack NuGet package
  inputs:
    command: pack
    packagesToPack: 'src/Adliance.Storyblok/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: Push to public NuGet
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Public NuGet'
