name: 3.0.$(rev:r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: UseDotNet@2
  displayName: "Install .NET 5.0.x"
  inputs:
    version: '5.0.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  env:
    Adliance_Storyblok_Tests__ApiKeyPublic: $(ApiKeyPublic)

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: 'src/Adliance.Storyblok/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: Push
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Public NuGet'
