name: 0.0.1.$(rev:r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:
- job: Build_and_Test
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

- job: Pack
  dependsOn: Build_and_Test
  steps:
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
  - task: DotNetCoreCLI@2
    displayName: 'DotNet Pack'
    inputs:
      command: pack
      packagesToPack: 'src/Saxx.Storyblok/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
      versioningScheme: byBuildNumber

- job: Publish
  dependsOn: Pack
  steps:
  - task: NuGetCommand@2
    displayName: 'NuGet Push'
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'Public NuGet'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
